name: Build Gradle project

on:
  push:
    branches: [ "main" ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
      
    - name : Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run build with Gradle Wrapper
      working-directory: ./helloworld
      run: ./gradlew clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: helloworld
        path: ./helloworld/build/libs/helloworld.jar

    - name: Build the Docker image
      run: docker build . --file ./helloworld/Dockerfile --tag dvande820625/devops-interview:latest

    - name: Docker Push
      run: docker push dvande820625/dvande8206-devops-interview:latest
